from __future__ import annotations

from dataclasses import dataclass
from enum import Enum

import numpy as np


class CameraId(str, Enum):
    """
    Identifier of an event camera in a stereo setup.
    """

    LEFT = "left"
    RIGHT = "right"


@dataclass(slots=True)
class EventBatch:
    """
    A batch of events from one camera.

    Project conventions:
    - timestamps are stored in seconds as float64,
    - x and y are pixel coordinates,
    - polarity is stored as bool:
        True  -> positive event,
        False -> negative event.
    """

    t: np.ndarray
    x: np.ndarray
    y: np.ndarray
    p: np.ndarray
    camera: CameraId

    def __post_init__(self) -> None:
        self.camera = CameraId(self.camera)

        self.t = np.asarray(self.t, dtype=np.float64).reshape(-1)
        self.x = np.asarray(self.x, dtype=np.int32).reshape(-1)
        self.y = np.asarray(self.y, dtype=np.int32).reshape(-1)

        p_arr = np.asarray(self.p).reshape(-1)
        if p_arr.dtype == np.bool_:
            self.p = p_arr.astype(np.bool_)
        else:
            self.p = (p_arr > 0).astype(np.bool_)

        n_events = len(self.t)
        if not (len(self.x) == len(self.y) == len(self.p) == n_events):
            raise ValueError(
                "EventBatch arrays must have the same length: "
                f"len(t)={len(self.t)}, len(x)={len(self.x)}, "
                f"len(y)={len(self.y)}, len(p)={len(self.p)}"
            )

    def __len__(self) -> int:
        return len(self.t)

    @property
    def is_empty(self) -> bool:
        return len(self) == 0

    @property
    def time_range(self) -> tuple[float, float] | None:
        if self.is_empty:
            return None

        return float(self.t[0]), float(self.t[-1])

    @property
    def xy(self) -> np.ndarray:
        if self.is_empty:
            return np.empty((0, 2), dtype=np.float32)

        return np.column_stack((self.x, self.y)).astype(np.float32)

    @property
    def polarity_signed(self) -> np.ndarray:
        """
        Return event polarity encoded as -1 / +1.
        """
        return np.where(self.p, 1, -1).astype(np.int8)

    def slice_time(self, t_start: float, t_end: float) -> EventBatch:
        """
        Return events from the half-open interval [t_start, t_end).
        """
        mask = (self.t >= t_start) & (self.t < t_end)

        return EventBatch(
            t=self.t[mask],
            x=self.x[mask],
            y=self.y[mask],
            p=self.p[mask],
            camera=self.camera,
        )

    @classmethod
    def empty(cls, camera: CameraId) -> EventBatch:
        return cls(
            t=np.empty(0, dtype=np.float64),
            x=np.empty(0, dtype=np.int32),
            y=np.empty(0, dtype=np.int32),
            p=np.empty(0, dtype=np.bool_),
            camera=camera,
        )


@dataclass(slots=True)
class StereoEventWindow:
    """
    A synchronized time window with events from both stereo cameras.

    This is the input object for the event aggregation stage.
    """

    t_start: float
    t_end: float
    left: EventBatch
    right: EventBatch

    def __post_init__(self) -> None:
        self.t_start = float(self.t_start)
        self.t_end = float(self.t_end)

        if self.t_end <= self.t_start:
            raise ValueError(
                f"Invalid event window: t_start={self.t_start}, t_end={self.t_end}"
            )

        if self.left.camera != CameraId.LEFT:
            raise ValueError("The left EventBatch must have camera=CameraId.LEFT")

        if self.right.camera != CameraId.RIGHT:
            raise ValueError("The right EventBatch must have camera=CameraId.RIGHT")

    @property
    def duration(self) -> float:
        return self.t_end - self.t_start

    @property
    def event_count(self) -> int:
        return len(self.left) + len(self.right)

    @property
    def is_empty(self) -> bool:
        return self.left.is_empty and self.right.is_empty


@dataclass(slots=True)
class EventFrame:
    """
    A grayscale image generated by aggregating events from one camera.

    The image is expected to be mono8, represented as a uint8 array of shape (H, W).
    """

    image: np.ndarray
    t_start: float
    t_end: float
    camera: CameraId
    frame_type: str = "standard"

    def __post_init__(self) -> None:
        self.camera = CameraId(self.camera)
        self.t_start = float(self.t_start)
        self.t_end = float(self.t_end)

        self.image = np.asarray(self.image)

        if self.image.ndim != 2:
            raise ValueError(
                f"EventFrame image must be a 2D grayscale image, got {self.image.shape}"
            )

        if self.image.dtype != np.uint8:
            raise ValueError(
                f"EventFrame image must have dtype uint8, got {self.image.dtype}"
            )

        if self.t_end <= self.t_start:
            raise ValueError(
                f"Invalid EventFrame time range: {self.t_start} -> {self.t_end}"
            )

    @property
    def height(self) -> int:
        return int(self.image.shape[0])

    @property
    def width(self) -> int:
        return int(self.image.shape[1])

    @property
    def shape(self) -> tuple[int, int]:
        return self.image.shape

    @property
    def timestamp(self) -> float:
        """
        Return the representative timestamp of this frame.

        For fixed event windows, the midpoint is a stable and simple convention.
        """
        return 0.5 * (self.t_start + self.t_end)


@dataclass(slots=True)
class StereoEventFrame:
    """
    A pair of left/right event frames for the same time window.

    This object will be passed to rectification, stereo depth estimation and VO.
    """

    left: EventFrame
    right: EventFrame

    def __post_init__(self) -> None:
        if self.left.camera != CameraId.LEFT:
            raise ValueError("The left EventFrame must have camera=CameraId.LEFT")

        if self.right.camera != CameraId.RIGHT:
            raise ValueError("The right EventFrame must have camera=CameraId.RIGHT")

        if self.left.shape != self.right.shape:
            raise ValueError(
                f"Left and right frames must have the same shape, got "
                f"{self.left.shape} and {self.right.shape}"
            )

    @property
    def t_start(self) -> float:
        return max(self.left.t_start, self.right.t_start)

    @property
    def t_end(self) -> float:
        return min(self.left.t_end, self.right.t_end)

    @property
    def timestamp(self) -> float:
        return 0.5 * (self.t_start + self.t_end)

    @property
    def shape(self) -> tuple[int, int]:
        return self.left.shape

    @property
    def height(self) -> int:
        return self.left.height

    @property
    def width(self) -> int:
        return self.left.width